# Generated by Django 4.1.2 on 2023-10-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0002_alter_purchase2_author_alter_purchase2_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase2',
            name='book_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_as_title', to='amsapp.book2'),
        ),
    ]
